### PR TITLE
Fix TODOs for reputation mining submission windows

### LINKED ISSUE #292: Fix withinTarget timestamp TODO
## Summary

```
  modifier withinTarget(bytes32 newHash, uint256 entryIndex) {
    require(reputationMiningWindowOpenTimestamp > 0);
    // Check the ticket is a winning one.
    // TODO Figure out how to uncomment the next line, but not break tests sporadically.
    // require((now-reputationMiningWindowOpenTimestamp) <= 3600);
```

### PR DESCRIPTION
**Pull request by kronosapiens**
Closes #292 #321

### CODE REVIEW

**Comment by kronosapiens** [comment]
Noting that this PR is also being extended to include this todo:

https://github.com/JoinColony/colonyNetwork/blob/develop/contracts/ReputationMiningCycle.sol#L226

File: test/colony-network-mining.js [hunk 1]
```diff
@@ -668,40 +696,34 @@ contract("ColonyNetworkMining", accounts => {
...
-      await repCycle.submitRootHash("0x12345678", 10, 8);
-      await repCycle.submitRootHash("0x12345678", 10, 9);
-      await repCycle.submitRootHash("0x12345678", 10, 10);
-      await repCycle.submitRootHash("0x12345678", 10, 11);
-      await repCycle.submitRootHash("0x12345678", 10, 12);
-      await checkErrorRevert(repCycle.submitRootHash("0x12345678", 10, 13), "colony-reputation-mining-max-number-miners-reached");
+      let entryNumber = await getValidEntryNumber(colonyNetwork, MAIN_ACCOUNT, "0x12345678", 1);
+      for (let i = 1; i <= 12; i += 1) {
+        await repCycle.submitRootHash("0x12345678", 10, entryNumber); // eslint-disable-line no-await-in-loop
+        entryNumber = await getValidEntryNumber(colonyNetwork, MAIN_ACCOUNT, "0x12345678", entryNumber + 1); // eslint-disable-line no-await-in-loop
```
Comment (elenadimitrova) [inline test/colony-network-mining.js]: This iteration got me confused. I _think_ what you're doing here is starting from the first available `entryNumber` and continuing until there are `12` but if so why not iterate from `entryNumber` to `12` instead of `1` to `12`?

File: test/colony-network-mining.js [hunk 2]
```diff
@@ -1506,8 +1544,12 @@ contract("ColonyNetworkMining", accounts => {
       await badClient.initialise(colonyNetwork.address);
       await goodClient.addLogContentsToReputationTree();
       await badClient.addLogContentsToReputationTree();
+
+      await forwardTime(3540, this);
       await goodClient.submitRootHash();
       await badClient.submitRootHash();
+      await forwardTime(60, this);
```
Comment (elenadimitrova) [inline test/colony-network-mining.js]: Any reason why you've squeezed in the hash submissions into smaller time here than the other tests?

File: contracts/ReputationMiningCycle.sol [hunk 3]
```diff
@@ -178,7 +182,8 @@ contract ReputationMiningCycle is ReputationMiningCycleStorage, PatriciaTreeProo
   function confirmNewHash(uint256 roundNumber) public
   finalDisputeRoundCompleted(roundNumber)
   {
-    // TODO: Require some amount of time to have passed (i.e. people have had a chance to submit other hashes)
+    require(submissionWindowClosed(), "colony-reputation-mining-submission-window-still-open");
```
Comment (elenadimitrova) [inline contracts/ReputationMiningCycle.sol]: This is not been tested for failure.

File: contracts/ReputationMiningCycle.sol [hunk 4]
```diff
@@ -72,19 +72,22 @@ contract ReputationMiningCycle is ReputationMiningCycleStorage, PatriciaTreeProo
   /// @dev A submission will only be accepted from a reputation miner if `keccak256(address, N, hash) < target`
   /// At the beginning of the submission window, the target is set to 0 and slowly increases to 2^256 - 1 after an hour
   modifier withinTarget(bytes32 newHash, uint256 entryIndex) {
-    require(reputationMiningWindowOpenTimestamp > 0, "colony-reputation-mining-cycle-not-open");
     // Check the ticket is a winning one.
-    // TODO Figure out how to uncomment the next line, but not break tests sporadically.
-    // require((now-reputationMiningWindowOpenTimestamp) <= 3600);
-    // x = floor(uint((2**256 - 1) / 3600)
-    if (now - reputationMiningWindowOpenTimestamp <= 3600) {
+    if (!submissionWindowClosed()) {
```
[the remark this answers is not in the document]
Comment (area) [reply contracts/ReputationMiningCycle.sol]: If no submission has been made to the current cycle, but the window has been open for more than an hour, submissionsOpen() does not throw. In that case, the calculation of `target` would overflow, and most submissions would be ineligible again. We want to bypass the eligibility check after the window has been open for an hour, hence this check.

Perhaps renaming `submissionWindowClosed` to `minimumSubmissionWindowElapsed` would  make this easier to understand what's happening?

File: packages/reputation-miner/ReputationMiner.js [hunk 5]
```diff
@@ -489,17 +496,56 @@ class ReputationMiner {
...
-    const repCycle = new ethers.Contract(addr, this.repCycleContractDef.abi, this.realWallet);
+    return new ethers.Contract(addr, this.repCycleContractDef.abi, this.realWallet);
+  }
+
+  /**
+   * Submit what the client believes should be the next reputation state root hash to the `ReputationMiningCycle` contract
+   * @param startIndex What index to start searching at when looking for a valid submission
+   * @return {Promise}
+   */
+  async submitRootHash(startIndex = 1) {
```
[the remark this answers is not in the document]
Comment (area) [reply packages/reputation-miner/ReputationMiner.js]: The intention here is for this parameter to be passed with the index after any index they have already submitted to the current cycle, in order to avoid attempting to resubmit a hash with an index they have already used.

Upon reflection, this isn't strictly optimal behaviour for the miner - it skips any earlier entries that might now be valid that were not valid earlier. I think that behaviour change would be more appropriate in the 'autonomous mining' work I'm intending to do as part of #211.

File: test/colony-network-mining.js (hunk 1 above)
Comment (area) [reply test/colony-network-mining.js]: `entryNumber` relates to which 'set' of `10**15` CLNY are used to submit an entry. The twelve entires might involve sets 1, 5, 13, 300, 341, 444, 510, 630, 635, 687, 731, 899. You are right that we want twelve to be submitted, but the entryNumber has (almost) no relation to the `i` being counted here (which is the number of the submission that is about to be made).

Again, perhaps you're being tripped up by my bad naming here 😢

File: test/colony-network-mining.js (hunk 2 above)
Comment (area) [reply test/colony-network-mining.js]: No reason. I think this is just a relic from initial tinkering. Will change to 3500 which is at least consistent with a lot of the others. Even doing that though, looks like we've ended up with a split between skips of 3500/100 and 1800/1800... shall I make those consistent where possible (which should be most places)?

Comment (elenadimitrova) [reply test/colony-network-mining.js]: yes please! Considering we'll be likely changing this timeframe to more than an hour, it maybe worth extracting this logic of submissions into a helper like here https://github.com/JoinColony/colonyNetwork/pull/357/files#diff-15aaaaa81a55d904a938772d3e2a3a82R2855?

File: contracts/ReputationMiningCycle.sol (hunk 4 above)
[the remark this answers is not in the document]
Comment (elenadimitrova) [reply contracts/ReputationMiningCycle.sol]: Or keep the window open until either we have 1 submission or time has elapsed, whichever is sooner?
