### PR TITLE
Fixed Restore good state in reputation mining test.

### LINKED ISSUE #524: Restore good state in reputation mining tests
In mining tests, work on restoring good state even after a test fails. Currently the test run exits on test failure.

### PR DESCRIPTION
**Pull request by dev1644**
Moved the logic of `before` block into a function `newNetworkInstance`, if we ever reached to a point from where we can't untangle the disputed states, we will call this function which will reset the network completely. 

Closes #524

### CODE REVIEW

**Comment by elenadimitrova** [comment]
Thanks @dev1644 . It's a working solution with `ganache-cli` however as @area pointed out to me earlier this won't work with `parity` or `geth` as neither supports `evm_revert`. Sorry this wasn't explicitly in the description but we have a [working item to get our nightly builds to run against a production client here](https://github.com/JoinColony/colonyNetwork/issues/319) and using `evm_revert` will take us a step away from being able to achieve this.

Instead, can we try just replicating what the `before` section in mining tests does in terms of resetting the network. This is what I originally meant with [this](https://github.com/JoinColony/colonyNetwork/issues/524#issuecomment-479848147) comment although I see now that wasn't completely clear.

**Comment by dev1644** [comment]
Ok, So replicating the `before` section will do the trick, right? I am on it.

File: test/reputation-mining/root-hash-submissions.js [hunk 1]
```diff
@@ -95,7 +99,8 @@ contract("Reputation mining - root hash submissions", accounts => {
   });
 
   afterEach(async () => {
-    await finishReputationMiningCycleAndWithdrawAllMinerStakes(colonyNetwork, this);
+    const shouldSetupNewInstance = await finishReputationMiningCycleAndWithdrawAllMinerStakes(colonyNetwork, this);
+    if (!shouldSetupNewInstance) await newNetworkInstance(MINER1, MINER2, MINER3);
```
Comment (elenadimitrova) [inline test/reputation-mining/root-hash-submissions.js]: `shouldSetupNewInstance ` isn't representative of what the result is here, and so the next line doesn't read right too in that "if not shouldSetupNewInstance then setupNewInstance"..
Maybe simply rename to `success` or `reputationMiningClean`?

Comment (dev1644) [reply test/reputation-mining/root-hash-submissions.js]: You are right, `shouldSetupNewInstance` should be renamed.

Comment (elenadimitrova) [reply test/reputation-mining/root-hash-submissions.js]: And another thing `shouldSetupNewInstance` is always coming back as `undefined` irrespective of whether `finishReputationMiningCycleAndWithdrawAllMinerStakes` succeeded or failed. This should be changed to return boolean as the check now requires.

Comment (dev1644) [reply test/reputation-mining/root-hash-submissions.js]: All Fixed!
