### PR TITLE
Big Old Test Refactor 1

### LINKED ISSUE #317: Test suite refactoring
This is a living issue to keep track of any ideas around making our test suite better

- [x] Simplify the test data setup to use the new `makeTask` overloads and not set the `dueDate` via a signed transaction, e.g. in https://github.com/JoinColony/colonyNetwork/pull/315/files#diff-c973fa0b369a707dd3dcba1d13c542bfL60
- [x] @area pointed out the `colony-reputation-mining-failed-to-respond-in-time` error message shows when the submission in question has not yet failed to respond whereas the message definitely makes it sound like it has. Maybe `colony-reputation-mining-challenge-not-timed-out` is more appropriate?
- [x] Check there are no simple `assert()`s and everything is `assert.isTrue` 
- [x] For the mining tests, explore other ways to `giveUserCLNYTokensAndStake` rather than completing a task. Possibly if we create the token authority for the CLNY token and allow the coinbase account to call `mint`, we can achieve that. Currently it complicates our reputation mining tests as these task completions incur reputation changes.
Note that as part of #387 we are already introducing the CLNY Authority as defined in the colonyToken repo. 
- [x] In mining tests, when a bad client fails to complete a challenge, we should check the error returned is what we expect, e.g. in `respondToChallenge` function the bad client should get back an error it's failing at the point we are testing. Also outlined by @area [here](https://github.com/JoinColony/colonyNetwork/issues/201#issuecomment-408474449)
- [x] General refactoring of the entire main test suite to get rid of unnecessary setup and checks in tests and focus on _unit_ testing as some tests feel more like integration testing. e.g. Decide if we really need the `colony.js`, `metacolony.js`, `reputation-change.js` tests to redeploy an entire network at the start of every test.
- [x] Look for ways to speed up coverage testing, e.g. exclude tests that are not testing contract functionality such as the reputation mining client test set 
- [x] At the very least investigate and maybe complete the work for bringing test coverage up to as close to 100% as possible. Log any new issues for distinct pieces of logic that need covering if it proves too much for the scope of this work.
- [x] Add test coverage and checks for the reputation mining client (logged as https://github.com/JoinColony/colonyNetwork/issues/523)
- [x] In mining tests, work on restoring good state even after a test fails. Currently if a test fails in `colony-network-mining.js` test fails, the test run exits. (logged separately as https://github.com/JoinColony/colonyNetwork/issues/524)

### PR DESCRIPTION
**Pull request by kronosapiens**
Partial soln to #317 

- Remove circular dependency between `constants.js` and `test-helper.js`
- Utilize bulk assignment of task properties when generating tasks (10-15% speedup).
- Replace `assert` with `assert.isTrue`.
- Clarify a reputation mining error message re: timeouts.
- Introduce `setupFinalizedTask` to remove recurring boilerplate.
- Introduce `advanceMiningCycleNoContest` and `getActiveRepCycle` to remove recurring boilerplate.

### CODE REVIEW

File: test/reputation-update.js [hunk 1]
```diff
@@ -201,51 +197,39 @@ contract("Colony Reputation Updates", accounts => {
...
-      const maxUIntNumber = new BN(2).pow(new BN(255)).sub(new BN(1));
-      await fundColonyWithTokens(metaColony, colonyToken, maxUIntNumber);
-      // Split the tokens as payouts between the manager and worker
+      await fundColonyWithTokens(metaColony, colonyToken, INT256_MAX);
+
+      // Split the tokens as payouts between the manager, evaluator, and worker
       const managerPayout = new BN("2");
       const evaluatorPayout = new BN("1");
-      const workerPayout = maxUIntNumber.sub(managerPayout).sub(evaluatorPayout);
+      const workerPayout = INT256_MAX.sub(managerPayout).sub(evaluatorPayout);
```
Comment (elenadimitrova) [inline test/reputation-update.js]: Why an int max rather than uint max?

Comment (kronosapiens) [reply test/reputation-update.js]: Because reputation is based on `ints`, so using `UINT256_MAX` would be interpreted as a negative value.

Comment (elenadimitrova) [reply test/reputation-update.js]: Okay yes, it's just a badly named old variable, i.e. `maxUIntNumber`

File: test/colony-network-recovery.js [hunk 2]
```diff
@@ -250,28 +239,16 @@ contract("Colony Network Recovery", accounts => {
...
           await miningClient.addLogContentsToReputationTree();
-          await forwardTime(MINING_CYCLE_DURATION, this);
-          await miningClient.submitRootHash();
-
-          addr = await colonyNetwork.getReputationMiningCycle.call(true);
-          repCycle = await IReputationMiningCycle.at(addr);
+          await advanceMiningCycleNoContest(colonyNetwork, this, miningClient);
 
+          const addr = await colonyNetwork.getReputationMiningCycle(true);
+          const repCycle = await IReputationMiningCycle.at(addr);
```
Comment (elenadimitrova) [inline test/colony-network-recovery.js]: Use the new `getActiveMineCycle` helper?

Comment (kronosapiens) [reply test/colony-network-recovery.js]: Ok updated

Comment (area) [reply test/colony-network-recovery.js]: There are a still a few places where a line or two could be saved with this pattern (e.g. https://github.com/JoinColony/colonyNetwork/pull/441/files#diff-15aaaaa81a55d904a938772d3e2a3a82R387) - basically, most (though not all) places where `getReputationMiningCycle(true)` still exists.

Comment (kronosapiens) [reply test/colony-network-recovery.js]: The only kicker is that we occasionally use `addr` in comparisons, but we could always drop in `repCycle.address`.

Comment (kronosapiens) [reply test/colony-network-recovery.js]: Alright, try this on for size

File: helpers/constants.js [hunk 3]
```diff
@@ -18,15 +18,18 @@ const MANAGER_RATING = 2;
 const WORKER_RATING = 3;
 const RATING_MULTIPLIER = { 1: -1, 2: 1, 3: 1.5 };
 const SECONDS_PER_DAY = 86400;
-const RATING_1_SALT = web3Utils.soliditySha3(getRandomString(10));
-const RATING_2_SALT = web3Utils.soliditySha3(getRandomString(10));
+const RATING_1_SALT = web3Utils.soliditySha3(shortid.generate());
+const RATING_2_SALT = web3Utils.soliditySha3(shortid.generate());
```
Comment (elenadimitrova) [inline helpers/constants.js]: When you rebase this pls use the `web3Utils` imports at the top rather than explicit references.

Comment (kronosapiens) [reply helpers/constants.js]: Kk
