### PR TITLE
Bring all dev dependencies up to date

### LINKED ISSUE #775: An in-range update of husky is breaking the build 🚨
## The devDependency [husky](https://github.com/typicode/husky) was updated from `4.0.9` to `4.0.10`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Fhusky-4.0.10).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

husky is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ✅ **Gas Usage:** ## Deployments
|                                  |       Gas |     | Diff | Diff % | Block % | usd avg |
| :------------------------------- | --------: | :-: | ---: | -----: | ------: | ------: |
| **ColonyNetwork**                | 5,119,192 |     |    - |      - |  76.2 % |    4.11 |
| **ColonyNetworkAuction**         | 2,152,989 |     |    - |      - |    32 % |    1.73 |
| **ColonyNetworkENS**             | 2,012,346 |     |    - |      - |  29.9 % |    1.62 |
| **ColonyNetworkMining**          | 2,435,071 |     |    - |      - |  36.2 % |    1.96 |
| **ContractRecovery**             | 1,196,203 |     |    - |      - |  17.8 % |    0.96 |
| **EtherRouter**                  |   442,602 |     |    - |      - |   6.6 % |    0.36 |
| **OneTxPayment**                 | 1,574,760 |     |    - |      - |  23.4 % |    1.26 |
| **OneTxPaymentFactory**          | 2,017,848 |     |    - |      - |    30 % |    1.62 |
| **ReputationMiningCycle**        | 5,948,905 |     |    - |      - |  88.5 % |    4.78 |
| **ReputationMiningCycleRespond** | 3,904,326 |     |    - |      - |  58.1 % |    3.14 |
| **Resolver**                     |   540,516 |     |    - |      - |     8 % |    0.43 |

## Methods
|                                            |       Gas |     | Diff | Diff % | Calls | usd avg |
| :----------------------------------------- | --------: | :-: | ---: | -----: | ----: | ------: |
| **Colony**                                 |           |     |      |        |       |         |
|        *addGlobalSkill*                    |    82,427 |     |    - |      - |     5 |    0.07 |
|        *bootstrapColony*                   |   333,507 |     |    - |      - |     1 |    0.27 |
|        *mintTokens*                        |    65,888 |     |    - |      - |     2 |    0.05 |
|        *setAdministrationRole*             |    52,554 |     |    - |      - |     4 |    0.04 |
|        *setAuthority*                      |    44,725 |     |    - |      - |     1 |    0.04 |
|        *setFundingRole*                    |    48,782 |     |    - |      - |     1 |    0.04 |
| **ColonyFunding**                          |           |     |      |        |       |         |
|        *claimColonyFunds*                  |    72,262 |     |    - |      - |     4 |    0.06 |
|        *claimPayment*                      |   102,727 |     |    - |      - |     1 |    0.08 |
|        *claimRewardPayout*                 |   164,276 |     |    - |      - |     2 |    0.13 |
|        *finalizeRewardPayout*              |    19,844 |     |    - |      - |     2 |    0.02 |
|        *moveFundsBetweenPots*              |    76,726 |     |    - |      - |     2 |    0.06 |
|        *startNextRewardPayout*             |   227,296 |     |    - |      - |     2 |    0.18 |
| **ColonyNetwork**                          |           |     |      |        |       |         |
|        *createColony*                      | 4,050,403 |     |    - |      - |     3 |    3.25 |
| **ColonyPayment**                          |           |     |      |        |       |         |
|        *addPayment*                        |   236,791 |     |    - |      - |     1 |    0.19 |
|        *finalizePayment*                   |   168,805 |     |    - |      - |     1 |    0.14 |
| **ColonyTask**                             |           |     |      |        |       |         |
|        *executeTaskChange*                 |    86,880 |     |    - |      - |     6 |    0.07 |
|        *executeTaskRoleAssignment*         |    97,710 |     |    - |      - |     1 |    0.08 |
|        *finalizeTask*                      |   577,984 |     |    - |      - |     2 |    0.46 |
|        *makeTask*                          |   338,086 |     |    - |      - |     1 |    0.27 |
|        *revealTaskWorkRating*              |    38,604 |     |    - |      - |     2 |    0.03 |
|        *submitTaskDeliverable*             |    72,604 |     |    - |      - |     1 |    0.06 |
|        *submitTaskWorkRating*              |    76,337 |     |    - |      - |     2 |    0.06 |
| **OneTxPayment**                           |           |     |      |        |       |         |
|        *makePayment*                       |   668,827 |     |    - |      - |     2 |    0.54 |
| **ReputationMiningCycle**                  |           |     |      |        |       |         |
|        *confirmBinarySearchResult*         |    75,829 |     |    - |      - |     4 |    0.06 |
|        *confirmJustificationRootHash*      |   139,614 |     |    - |      - |     3 |    0.11 |
|        *confirmNewHash*                    |   723,311 |     |    - |      - |     5 |    0.58 |
|        *invalidateHash*                    |   229,155 |     |    - |      - |     3 |    0.18 |
|        *respondToBinarySearchForChallenge* |   120,478 |     |    - |      - |    12 |    0.10 |
|        *submitRootHash*                    |   273,505 |     |    - |      - |     7 |    0.22 |
| **ReputationMiningCycleRespond**           |           |     |      |        |       |         |
|        *respondToChallenge*                |   191,844 |     |    - |      - |     2 |    0.15 |
| **TokenLocking**                           |           |     |      |        |       |         |
|        *deposit*                           |    70,061 |     |    - |      - |     5 |    0.06 |
|        *incrementLockCounterTo*            |    41,091 |     |    - |      - |     2 |    0.03 |
|        *withdraw*                          |   101,895 |     |    - |      - |     2 |    0.08 |

## Build Configuration
| Option                 | Settings              |
| ---------------------- | --------------------- |
| solc: version          | 0.5.8+commit.23d335f2 |
| solc: optimized        | true                  |
| solc: runs             | 200                   |
| gas: block limit       | 6,721,975             |
| gas: price             | 5 gwei/gas            |
| gas: currency/eth rate | 160.60 usd/eth        |

---

Target commit: *77bb0f01420d08e7ec2d1a04dd064a6e85cf404e*

Base commit: *3cdd656804cbf8bd4ae63ea8683a89bea7c07548* 
- ❌ **commit:** * [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10733?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10732?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success 
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 2 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/typicode/husky/commit/eaf9376a6c7ad311654b98e9c45864b5fdc48d9b"><code>eaf9376</code></a> <code>4.0.10</code></li>
<li><a href="https://urls.greenkeeper.io/typicode/husky/commit/2018ed9fec05c5b36b1e9d13041abbb29cbabdb4"><code>2018ed9</code></a> <code>fix pre-push</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/typicode/husky/compare/93b3fc6a704fa381668db39edcf3f4005b92fa44...eaf9376a6c7ad311654b98e9c45864b5fdc48d9b">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #777: An in-range update of ganache-cli is breaking the build 🚨
## The devDependency [ganache-cli](https://github.com/trufflesuite/ganache-cli) was updated from `6.8.1` to `6.8.2`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Fganache-cli-6.8.2).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

ganache-cli is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10752?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10753?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success 
</details>

---

<details>
<summary>Release Notes for v6.8.2 - Hotfix 🔥</summary>

<h4>
  <p align="center">
		<code> <a href="#user-content-v6.8.2-Highlights">Highlights</a> </code> 
		<a target="_blank" rel="noopener noreferrer" href="https://raw.githubusercontent.com/davidmurdoch/px/master/1px.gif"></a>
		<code> <a href="#user-content-v6.8.2-How-to-Upgrade">How to Upgrade</a> </code> 
		<a target="_blank" rel="noopener noreferrer" href="https://raw.githubusercontent.com/davidmurdoch/px/master/1px.gif"></a>
		<code> <a href="#user-content-v6.8.2-Changelog">Changelog</a> </code> 
		<a target="_blank" rel="noopener noreferrer" href="https://raw.githubusercontent.com/davidmurdoch/px/master/1px.gif"></a>
		<code> <a href="#user-content-v6.8.2-Related-Releases">Related Releases</a> </code>
		<a target="_blank" rel="noopener noreferrer" href="https://raw.githubusercontent.com/davidmurdoch/px/master/1px.gif"></a>
  </p>
</h4>
<hr>
<p>We're moving to a <code>beta</code> › <code>latest</code> release pipeline, where all non-hotfix changes are first released in a beta before being promoted to a stable release.</p>
<p>We'd love it if you'd start using the latest betas and let us know early and often if you find any bugs or regressions!</p>
<h2><a name="user-content-v6.8.2-Highlights"></a>Highlights</h2>
<p>The previous release, v6.8.1, changed the way <code>chainId</code>'s (the <code>v</code> value) were handled for raw transactions which in turn was preventing them from being accepted in certain situations. This fixes this issue and reverts the change that enabled EIP-155 replay protection in order to preserve backwards compatibility. Additionally, the mismatch of between ganache-cli's hardcoded <code>chainId</code> and its default <code>net_version</code> caused metamask signed transactions to always fail. Ganache-cli will accept any <code>v</code> value as it used to prior to v6.8.2.</p>
<p>This behavior will change in the next major release of ganache-cli and the default behavior will be to validate the <code>v</code> value of raw transactions against the configured <code>chainId</code>.</p>
<hr>
<h2><a name="user-content-v6.8.2-How-to-Upgrade"></a>How to Upgrade</h2>
<p>Upgrade to the latest version of ganache-cli by running:</p>
<h4>npm</h4>
<div class="highlight highlight-text-shell-session"><pre><span class="pl-c1">npm uninstall ganache-cli -g</span>
<span class="pl-c1">npm install ganache-cli@latest -g</span></pre></div>
<h4>yarn</h4>
<div class="highlight highlight-text-shell-session"><pre><span class="pl-c1">yarn global remove ganache-cli</span>
<span class="pl-c1">yarn global add ganache-cli@latest</span></pre></div>
<h2><a name="user-content-v6.8.2-Changelog"></a>Changelog</h2>
<h3>Bug Fixes</h3>
<ul>
<li>Fix Incompatible EIP155-based V RPC Error (<a class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="550449709" data-permission-text="Issue title is private" data-url="https://github.com/trufflesuite/ganache-core/issues/532" data-hovercard-type="pull_request" data-hovercard-url="/trufflesuite/ganache-core/pull/532/hovercard" href="https://urls.greenkeeper.io/trufflesuite/ganache-core/pull/532">trufflesuite/ganache-core#532</a>) – <a class="user-mention" data-hovercard-type="user" data-hovercard-url="/users/nicholasjpaterno/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://urls.greenkeeper.io/nicholasjpaterno">@nicholasjpaterno</a>  and <a class="user-mention" data-hovercard-type="user" data-hovercard-url="/users/davidmurdoch/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://urls.greenkeeper.io/davidmurdoch">@davidmurdoch</a></li>
</ul>
<h2><a name="user-content-v6.8.2-Related-Releases"></a>Related Releases</h2>
<ul>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/releases/tag/v2.9.2">ganache-core v2.9.2</a></li>
</ul>
<hr>
<p align="center">
  <g-emoji class="g-emoji" alias="sparkling_heart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f496.png">💖</g-emoji> The Truffle Team
</p>
<p><a target="_blank" rel="noopener noreferrer" href="https://camo.githubusercontent.com/72cdb9913f1348dcf6f3996f9b2ce45963de24ad/68747470733a2f2f73736c2e676f6f676c652d616e616c79746963732e636f6d2f636f6c6c6563743f763d3126743d6576656e742665633d67616e616368652d636c692d72656c656173652d6e6f7465732665613d7669657726743d6576656e74267469643d55412d38333837343933332d33267a3d31353535363839333832266369643d38653936623331662d663835372d346534622d393532302d6466356364336135326166302664743d76362e382e322532302d25486f746669782664703d2f6769746875622e636f6d2f"></a></p>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 3 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/ccba1433acbfb2cc512d43442669c321c81235ed"><code>ccba143</code></a> <code>6.8.2</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/9f788a0dcef49671bf4164785471659d0457ed59"><code>9f788a0</code></a> <code>Update ganache-core to v2.9.2</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/commit/a7eba57eb0366de384f2abb8c8ff460ef21db29c"><code>a7eba57</code></a> <code>Update default hardfork to <code>istanbul</code></code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/trufflesuite/ganache-cli/compare/15f2e766c0096d5028f1a1b00dcfc8bf4148c3fe...ccba1433acbfb2cc512d43442669c321c81235ed">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #785: An in-range update of truffle is breaking the build 🚨
## The devDependency [truffle]() was updated from `5.1.9` to `5.1.10`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Ftruffle-5.1.10).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

truffle is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10839?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10838?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed 
</details>

---

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #787: An in-range update of web3-utils is breaking the build 🚨
## The dependency [web3-utils]() was updated from `1.2.4` to `1.2.5`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Fdefault%2Fweb3-utils-1.2.5).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

web3-utils is a direct dependency of this project, and **it is very likely causing it to break**. If other packages depend on yours, this update is probably also breaking those in turn.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10851?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success
* [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10850?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed 
</details>

---

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #788: An in-range update of rimraf is breaking the build 🚨
## The devDependency [rimraf](https://github.com/isaacs/rimraf) was updated from `3.0.0` to `3.0.1`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Frimraf-3.0.1).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

rimraf is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10857?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10856?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed 
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 4 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/isaacs/rimraf/commit/d709272f6122b008de66650616fda34c8ae6f954"><code>d709272</code></a> <code>3.0.1</code></li>
<li><a href="https://urls.greenkeeper.io/isaacs/rimraf/commit/692915dc5593326f0053f6fc7a9eda32d5de4ff1"><code>692915d</code></a> <code>funding</code></li>
<li><a href="https://urls.greenkeeper.io/isaacs/rimraf/commit/d82bc81f251ba2cc86dc26361a820631091b3e9e"><code>d82bc81</code></a> <code>changelog</code></li>
<li><a href="https://urls.greenkeeper.io/isaacs/rimraf/commit/3d4af4133f1e015a610aba7a7a6e490fdd5534bd"><code>3d4af41</code></a> <code>update travis.yml</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/isaacs/rimraf/compare/191ae6979d93330b5afeb6886e70047a98bb5253...d709272f6122b008de66650616fda34c8ae6f954">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #789: An in-range update of eslint-config-prettier is breaking the build 🚨
## The devDependency [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) was updated from `6.9.0` to `6.10.0`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Feslint-config-prettier-6.10.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

eslint-config-prettier is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10860?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10861?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success 
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 4 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/prettier/eslint-config-prettier/commit/95a476e1602e6364917e5f756d17dc41c9bbaeb6"><code>95a476e</code></a> <code>eslint-config-prettier v6.10.0</code></li>
<li><a href="https://urls.greenkeeper.io/prettier/eslint-config-prettier/commit/b7e3e9049673b9d2c5b9dce0a7c01a142d2c1c92"><code>b7e3e90</code></a> <code>Update npm packages</code></li>
<li><a href="https://urls.greenkeeper.io/prettier/eslint-config-prettier/commit/04c79bf1602c8126da863d0997aef5ff347b73db"><code>04c79bf</code></a> <code>Disable <code>@typescript-eslint/comma-spacing</code> (#135)</code></li>
<li><a href="https://urls.greenkeeper.io/prettier/eslint-config-prettier/commit/d89bb1018431530759f6d3f72ef27ad29f2018e1"><code>d89bb10</code></a> <code>Bump eslint from 6.6.0 to 6.8.0 (#136)</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/prettier/eslint-config-prettier/compare/5cf39be323b5bdd3208e5519cf539026edaf289d...95a476e1602e6364917e5f756d17dc41c9bbaeb6">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #792: An in-range update of ganache-core is breaking the build 🚨
## The dependency [ganache-core](https://github.com/trufflesuite/ganache-core) was updated from `2.9.2` to `2.10.0`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Fdefault%2Fganache-core-2.10.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

ganache-core is a direct dependency of this project, and **it is very likely causing it to break**. If other packages depend on yours, this update is probably also breaking those in turn.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10872?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success
* [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10873?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed 
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 23 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/a63522bb2cc5cc0ef7e26bd2c73a3e412a10dd2c"><code>a63522b</code></a> <code>2.10.0</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/c180f22e97e68dc0e89969f0b3142dbbfa2d4ab8"><code>c180f22</code></a> <code>fix:prevent hang during process exit due to tmp file cleanup (#542)</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/80df7f8090eaaf1947738bf16b94d7046758f0b2"><code>80df7f8</code></a> <code>Fix issue where tmp has to clean up too many files</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/c3823611b9bdfcb66ecfc4d1b2fc53a19faca90b"><code>c382361</code></a> <code>Remove extra graceful shutdown config</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/9a4a991a4f6fee11f16908fd5b2480f69b828852"><code>9a4a991</code></a> <code>Change VM hardfork default to <code>muirGlacier</code> (#541)</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/144745a52c8e9521817cd25b54bd7fd4c3d1a4c9"><code>144745a</code></a> <code>fix:slow tests sometimes timeout (#537)</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/27d59d974664462d4152d9bb6ca213e1a6fc9b55"><code>27d59d9</code></a> <code>Update dev dependencies &amp; fix linting issues (#539)</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/6964e6cfc87c483b789735764cf8fd895a747ff1"><code>6964e6c</code></a> <code>Add MuirGlacier support, Upgrade ethereumjs-*@latest and upgrade solc to v0.6.1 (#538)</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/4cf433891fc3b2d131f9ee4af75df50d16cbb55b"><code>4cf4338</code></a> <code>Merge branch 'beta' into develop</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/e2c10cb65917de31f86581aca17de2f8a31c9655"><code>e2c10cb</code></a> <code>2.9.3-beta.0</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/2f837b973591ad756a64fbf0737830b9a8b41ee2"><code>2f837b9</code></a> <code>Update dependencies</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/a25c1728e25f9941ac5da2eba5b38cce6c46930b"><code>a25c172</code></a> <code>misc:test mac and windows on travis too, EPERM fixes (#535)</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/c1db7850d10327db5e81467d749e680afa29da5b"><code>c1db785</code></a> <code>fix: windows EPERM due to leaving file descriptor open</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/3142c4c60616753d94e52f67ece69da679090c03"><code>3142c4c</code></a> <code>2.9.2</code></li>
<li><a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/commit/e44405631edbd83b72dcd4e88b2470b67eefeb2b"><code>e444056</code></a> <code>Fix Incompatible EIP155-based V RPC Error (#532)</code></li>
</ul>
<p>There are 23 commits in total.</p>
<p>See the <a href="https://urls.greenkeeper.io/trufflesuite/ganache-core/compare/9be4eaba65aad590a7f4a97ae94075eca6cfea4f...a63522bb2cc5cc0ef7e26bd2c73a3e412a10dd2c">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #793: An in-range update of ethers is breaking the build 🚨
## The dependency [ethers](https://github.com/ethers-io/ethers.js) was updated from `4.0.43` to `4.0.44`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Fdefault%2Fethers-4.0.44).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

ethers is a direct dependency of this project, and **it is very likely causing it to break**. If other packages depend on yours, this update is probably also breaking those in turn.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10878?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10879?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed 
</details>

---

<details>
<summary>Release Notes for ethers/v4.0.44 (2020-01-29 22:01)</summary>

<ul>
<li>Fix backwards compatibility with certain parsed JSON objects passed into Interface and Contracts (<a href="https://urls.greenkeeper.io/ethers-io/ethers.js/issues/721" data-hovercard-type="issue" data-hovercard-url="/ethers-io/ethers.js/issues/721/hovercard">#721</a>; <a href="https://urls.greenkeeper.io/ethers-io/ethers.js/commit/0589b3102e2da702f4ac19a32c8b083faa6bbeea">0589b31</a>).</li>
<li>Updated ENS registry address for all networks (<a href="https://urls.greenkeeper.io/ethers-io/ethers.js/commit/df51b26fe71c33fb8aa610d95c4955647345ce0a">df51b26</a>).</li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 4 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/ethers-io/ethers.js/commit/748f89660ac4bf60175f936da755cf1a0d370f46"><code>748f896</code></a> <code>Updated expected balance in test cases.</code></li>
<li><a href="https://urls.greenkeeper.io/ethers-io/ethers.js/commit/2987925fa5ff4a96fadc289951a77d180e499541"><code>2987925</code></a> <code>Updated dist files.</code></li>
<li><a href="https://urls.greenkeeper.io/ethers-io/ethers.js/commit/0589b3102e2da702f4ac19a32c8b083faa6bbeea"><code>0589b31</code></a> <code>Fix backwards compatibility with certain parsed JSON objects passed into Interface and Contracts (#721).</code></li>
<li><a href="https://urls.greenkeeper.io/ethers-io/ethers.js/commit/df51b26fe71c33fb8aa610d95c4955647345ce0a"><code>df51b26</code></a> <code>Updated ENS registry address for all networks.</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/ethers-io/ethers.js/compare/b288ad9ba791073df2768c580abe9173c6b851f6...748f89660ac4bf60175f936da755cf1a0d370f46">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #794: An in-range update of babel7 is breaking the build 🚨
## There have been updates to the *babel7* monorepo:

 + - The `devDependency` [@babel/core](https://www.npmjs.com/package/@babel/core) was updated from `7.8.3` to `7.8.4`.
- The `devDependency` [@babel/node](https://www.npmjs.com/package/@babel/node) was updated from `7.8.3` to `7.8.4`.
- The `devDependency` [@babel/preset-env](https://www.npmjs.com/package/@babel/preset-env) was updated from `7.8.3` to `7.8.4`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Fdefault%2Fmonorepo.babel7-20200130124445).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

This monorepo update includes releases of one or more dependencies which all belong to the [babel7 group definition](https://github.com/greenkeeperio/monorepo-definitions).

babel7 is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10881?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10880?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success 
</details>

---

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #795: An in-range update of truffle-security is breaking the build 🚨
## The devDependency [truffle-security](https://github.com/consensys/truffle-security) was updated from `1.6.2` to `1.7.0`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Ftruffle-security-1.7.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

truffle-security is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10884?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10885?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success 
</details>

---

<details>
<summary>Release Notes for v1.7.0</summary>

<p>Can now use MYTHX_API_KEY environment variable for passing api key.</p>
<p>Can now use MYTHX_USERNAME for authentication.</p>
<p>Support for new MythX plans.</p>
<p>Removal of trial mode.</p>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 18 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/96f06eab98456c06740e326044300d4d2e6a1669"><code>96f06ea</code></a> <code>Logs update</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/0c13bc5458cffa50e124a8dcb88a9dc5d661089d"><code>0c13bc5</code></a> <code>Refactor env var logic and add username</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/eb937bff58d4c0da24c5e43899b00747688ef455"><code>eb937bf</code></a> <code>Documentation and logging update</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/3a64117869aaa72a83dc772337e7870017de782e"><code>3a64117</code></a> <code>API key documentation</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/20b0c0525ff29800f9d11e0a83279684026bb45b"><code>20b0c05</code></a> <code>Add env variable for api key</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/8812c054978a58962f09dc4ed790e900d8cc6a50"><code>8812c05</code></a> <code>Remove logs</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/4be4cdb0e133e471eda2d4b29dd1ee87c2fc5d58"><code>4be4cdb</code></a> <code>Add deep scan to options</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/0bb3d747de3d40b114bd8c432f7068fb1c13a935"><code>0bb3d74</code></a> <code>Merge branch 'master' of <a href="https://urls.greenkeeper.io/ConsenSys/truffle-security">https://github.com/ConsenSys/truffle-security</a></code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/2817066b8903691188c2d508db994f54775695d2"><code>2817066</code></a> <code>UX20-572</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/dd5b0fc33547642bc881ec2085acd9ce5004caf9"><code>dd5b0fc</code></a> <code>UX20-572</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/5f8cbca4b060580adf4206773f937c0d3b966be9"><code>5f8cbca</code></a> <code>Merge pull request #253 from ConsenSys/bernhard_1</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/09445f6629c050171b769d2d18867151f66a12b6"><code>09445f6</code></a> <code>Update wording of trial message, remove '8'</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/a42875c6603a3aaafaa8d6871f688d8ed111cb40"><code>a42875c</code></a> <code>Timeouts</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/99607e8f1ae97c27e73475bbc2b33765c2811839"><code>99607e8</code></a> <code>Trial messaging</code></li>
<li><a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/commit/b59b7dfb3aecd25cf0ceed91be673209ce6f28ad"><code>b59b7df</code></a> <code>Trial messaging</code></li>
</ul>
<p>There are 18 commits in total.</p>
<p>See the <a href="https://urls.greenkeeper.io/ConsenSys/truffle-security/compare/69b32922e7ca64f2e038dbf8cb769781b4d53755...96f06eab98456c06740e326044300d4d2e6a1669">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #797: An in-range update of eslint-plugin-import is breaking the build 🚨
## The devDependency [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) was updated from `2.20.0` to `2.20.1`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Feslint-plugin-import-2.20.1).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

eslint-plugin-import is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10902?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10903?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success 
</details>

---

<details>
<summary>Commits</summary>
<p>The new version differs by 23 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/45f08609e0dd79f2a061c3411a43169c20e80d3a"><code>45f0860</code></a> <code>Bump to v2.20.1</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/5d00854f3c59a497f0a850c6ccab01a012d6b8db"><code>5d00854</code></a> <code>[Fix] <code>order</code>: Fix alphabetize for mixed requires and imports</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/bbd166bfe2e5a12b58cbe803acda3e67e099562c"><code>bbd166b</code></a> <code>[Fix] <code>export</code>: Handle function overloading in <code>*.d.ts</code></code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/4665ec5a687d068e4e4ab19e3dbde7d0c65bbee4"><code>4665ec5</code></a> <code>[Fix] <code>no-absolute-path</code>: fix a crash with invalid import syntax</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/392c6b9c44b8fab54d973b9e344ce1c0c6d1a1cc"><code>392c6b9</code></a> <code>[Fix] <code>named</code>: for importing from a module which re-exports named exports from a <code>node_modules</code> module</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/cc5bde5a526136530ceb4966c4245eeb36c3fc2c"><code>cc5bde5</code></a> <code>[Tests] <code>named</code>: add failing test for #1446</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/aff3a467f0a7cb982b3e82ef3bf3732ee0fbf449"><code>aff3a46</code></a> <code>[meta] fix "files" field to include/exclude the proper files</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/986ba749fec01b5e49922c215e0c0de8db9562c1"><code>986ba74</code></a> <code>docs: fix a few spelling mistakes</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/6274d965340a7cedeb6e9a9d40e3df0b2a4275f1"><code>6274d96</code></a> <code>[Tests] set <code>eslint-plugin/consistent-output</code> lint rule to always require test case output assertions</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/a4d301bac81551d16be7cc4737d8c66e7b46c38a"><code>a4d301b</code></a> <code>[meta] add missing changelog links</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/2d424643b659b4bae542999c34425ab1485ae9c8"><code>2d42464</code></a> <code>[Tests] only run the linter once, not on every build</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/26f232bb678463c8030840ffbd1af491200dffa0"><code>26f232b</code></a> <code>[Tests] add eslint-plugin-eslint-plugin internally and fix violations</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/99647f1f9f5887e846182affb3f667343485bcee"><code>99647f1</code></a> <code>[Docs]: Update Tidelift language to enterprise</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/f84d4577dc94600e28b2071ae365d671bfc6420e"><code>f84d457</code></a> <code><code>no-duplicates</code>: allow duplicate if one is namespace and other not</code></li>
<li><a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/commit/7e71b5090d18c0736778c6c8b5301b00c06c880b"><code>7e71b50</code></a> <code>[Fix] <code>extensions</code>: Fix scope regex</code></li>
</ul>
<p>There are 23 commits in total.</p>
<p>See the <a href="https://urls.greenkeeper.io/benmosher/eslint-plugin-import/compare/8001916392c281f288eb5c33c6cf23dd7ab99673...45f08609e0dd79f2a061c3411a43169c20e80d3a">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #798: An in-range update of openzeppelin-solidity is breaking the build 🚨
## The devDependency [openzeppelin-solidity](https://github.com/OpenZeppelin/openzeppelin-contracts) was updated from `2.4.0` to `2.5.0`.

🚨 [View failing branch](https://github.com/JoinColony/colonyNetwork/compare/develop...JoinColony:greenkeeper%2Fopenzeppelin-solidity-2.5.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

openzeppelin-solidity is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **commit:** * [lint-and-unit-test](https://circleci.com/gh/JoinColony/colonyNetwork/10933?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Failed
* [test-coverage](https://circleci.com/gh/JoinColony/colonyNetwork/10934?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link) - Success 
</details>

---

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by area**
Closes #798, closes #797, closes #795, closes #794, closes #793, closes #792, closes #789, closes #788, closes #787, closes #785, closes #777, closes #775 which I'm going to claim as some sort of record. No-one correct me.

The only one of these issues that was real was around the ganache upgrade, which required several changes. 

- The Istanbul hard fork (and the changed gas cost for certain opcodes therein) causes the maximum number of skills able to be on a task and still closed in the block limit to be reduced from 45 to 42.
- The new ganache seems to be slightly slower under coverage (or circle machines are slower now), so I had to add interstitial output to a particularly long-running test to get it to pass reliably.
- It would seem the new ganache is bad at gas estimation again, so moved the 'if we're talking to ganache, add extra gas' logic to all calls in the miner.

### CODE REVIEW

**Comment by kronosapiens** [comment]
Shouldn't the dependencies in `package.json` be updated here? Or am I missing something?

**Comment by area** [comment]
Not necessarily, these are all in-range upgrades. So, for example, `^6.7.0`, which is listed for `ganache-cli` in `package.json` matches all versions up to `7.x`. This PR is doing an upgrade from `6.8.1` to `6.9.0`, so the `package.json` doesn't need changing - the `yarn.lock` controls which version is chosen from the valid available versions.

**Comment by kronosapiens** [comment]
@area mm I guess you're right -- I looked back over some of the GK PRs and they all mention that the new version is **not** covered by the version range.

File: packages/reputation-miner/ReputationMiner.js [hunk 1]
```diff
@@ -1182,6 +1192,14 @@ class ReputationMiner {
...
   }
 
+  padGasEstimateIfNecessary(_gasEstimate){
+    let gasEstimate = _gasEstimate;
+    if (this.ganacheClient) {
+      gasEstimate = `0x${new BN(gasEstimate.toString()).mul(new BN("11")).div(new BN("10")).toString(16)}`;
+    }
+    return gasEstimate;
+  }
+
```
Comment (kronosapiens) [inline packages/reputation-miner/ReputationMiner.js]: Why not just

```
  padGasEstimateIfNecessary(gasEstimate){
    if (this.ganacheClient) {
      return `0x${new BN(gasEstimate.toString()).mul(new BN("11")).div(new BN("10")).toString(16)}`;
    } else {
      return gasEstimate;
   }
  }
```

File: packages/reputation-miner/ReputationMiner.js [hunk 2]
```diff
@@ -103,6 +103,11 @@ class ReputationMiner {
     this.nReputations = ethers.constants.Zero;
     this.reputations = {};
     this.gasPrice = ethers.utils.hexlify(20000000000);
+
+    // Are we using ganache? If so, note this so we add safety margin to gas estimates because ganache sucks at that
+    // See if we're talking to Ganache to fix a ganache crash (which, while fun to say, is not fun to see)
+    const clientString = await this.realProvider.send("web3_clientVersion");
+    this.ganacheClient = clientString.indexOf('TestRPC') !== -1;
```
Comment (kronosapiens) [inline packages/reputation-miner/ReputationMiner.js]: Can this be `this.isGanacheClient` instead? `ganacheClient` suggests that the type of the variable is a client, not a boolean.

File: packages/reputation-miner/ReputationMiner.js [hunk 3]
```diff
@@ -640,6 +645,7 @@ class ReputationMiner {
     } catch (err) { // eslint-disable-line no-empty
 
     }
+    gasEstimate = this.padGasEstimateIfNecessary(gasEstimate);
```
Comment (kronosapiens) [inline packages/reputation-miner/ReputationMiner.js]: The term `IfNecessary` here seems unecessarily vague -- why not something like `padGanacheEstimate`, as the only branching condition is whether the client is ganache or not.
